version: '2'
services:
  bolo-service:
    image: ionic-project-docker-image
    command: ionic serve -b -p 8100 -r 8200 --address 0.0.0.0
    volumes:
      - .:/projects/ionic-project/
    ports:
      - "8100:8100"
      - "8200:8200"
    tty: true
